CREATE DATABASE IF NOT EXISTS bestiary;
USE bestiary;

DROP TABLE IF EXISTS size;
CREATE TABLE size(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    label VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS `type`;
CREATE TABLE `type`(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    label VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS  environment;
CREATE TABLE environment(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(25) NOT NULL
);